# Generated by Django 4.2.7 on 2025-08-02 15:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['item_name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='Item Picture'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='model',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='srp_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='SRP Price'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
    ]
