# Generated by Django 5.2.4 on 2025-08-03 02:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_inventory_options_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Discounted selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Discount Price'),
        ),
    ]
