# Generated by Django 5.2.4 on 2025-08-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.PositiveIntegerField(verbose_name='Quantity Bought')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Supplier')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchase Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.inventory', verbose_name='Item Purchased')),
            ],
            options={
                'verbose_name': 'Buy Item',
                'verbose_name_plural': 'Buy Items',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
