# Generated by Django 5.2.4 on 2025-08-03 12:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_buyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted selling price (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Discount Price'),
        ),
    ]
